### ISSUE TITLE
As a Consumer, I can perform a Simple Search

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1]
As a Consumer, I can perform a Simple Search using Name, Location (State, Region, Zip + Radius), and Size fields to view a resulting list of institutions matching my query. These results would show:  1) Name of School, 2) Location of School, 3) Type of Institution (2-year/4-year), 4) Undergraduate Population,

"From 2013derived_opeid6.csv fields:
name=INSTNM_MAIN
city=CITY_MAIN
state=STABBR_MAIN
zip=ZIP_MAIN
region=REGION_MAIN
type-of-institution=INSTCAT_MAIN
size=UGDS (undergraduate degree-seeking enrollment number).

From a user experience (story acceptance) perspective, this includes these smaller stories
- [x] Search by Name https://github.com/18F/college-choice/issues/35
- [x] Search by State https://github.com/18F/college-choice/issues/36
- [x] Search by multiple states https://github.com/18F/college-choice/issues/37
- [x] Search by distance from ZIP code https://github.com/18F/college-choice/issues/38
- [x] Search by region https://github.com/18F/college-choice/issues/282
- [x] search by size https://github.com/18F/college-choice/issues/279
- [x] search by major

Alternatively, 2013derived_opeid.csv has the same variables broken down by branch (possibly use _FREQ instead of _MAIN).  Data dictionary at https://docs.google.com/spreadsheets/d/1wIbBcnv-cMhmuF_8A1pFJ1vVi-W83PMayEz8hhBuKTY/edit#gid=802307363 (including interpretation for INSTCAT_MAIN field)"

Region is a number.. is there a mapping to words somewhere?  DN: The data dictionary at https://docs.google.com/spreadsheets/d/1wIbBcnv-cMhmuF_8A1pFJ1vVi-W83PMayEz8hhBuKTY/edit#gid=802307363  includes an interpretation for this column.

- [X] read csv files
- [ ] read 2012derived_opeid.csv
- [X] create elasticsearch index
- [X] search by attribute ( INSTNM_MAIN)
- [X] column name mapping
- [X] configure API endpoint
- [x] search by Name
- [x] search by state, zip
- [x] search by region
- [x] search by size
- [x] geolocation radius search

**Comment by diego-** [comment]
please break up search tasks into separate tickets; then close this ticket as duplicate. 

per sprint planning mtg., july 27, 2015

**Comment by ErieMeyer** [comment]
This is fixed!

Found one new bug that's unrelated though: 
https://github.com/18F/college-choice/issues/1083
