### ISSUE TITLE
Upload final documents/links on data tool

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#1015]
The MVP for the data tool is structurally done, but we will need to update links/downloads before launch. 

- [x] query samples #1220
- [x] pdfs for download (policy, tech, full documentation report) #1216
- [x] data dictionary csv #1192 
- [x] full data download, zip (includes all of the csvs, data dictionary, full report documentation, data.yml)
- [x] sample/subset csvs #1216
- [x] review 10 quotes in carousel. recommend choosing less than 10. #1195

**Comment by meiqimichelle** [comment]
@diego- I put you on here because I think you're tracking the documents?? feel free to reassign.

**Comment by diego-** [comment]
new cvs:
https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(All+Data+Elements).csv (124MB)
https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(NSLDS+Elements).csv (104.4MB)
https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(Scorecard+Elements).csv (4.6MB)
https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(Treasury+Elements).csv (7.4MB)

**Comment by diego-** [comment]
Raw data: https://s3.amazonaws.com/ed-college-choice-public/CollegeScorecard_Raw_Data.zip

**Comment by diego-** [comment]
Also added /assets/FullDataDocumentation.pdf in PR #1068

per @LisaGee:

This is the full Data Documentation file that should live in 2 places:
1.       Include the .PDF version as part of the Bulk Data Download (when downloading entire data set).

2.       I will also add it to this sentence on the Data Documentation page:

a.       For detailed information on each categories and its individual fields, see the Full Documentation and the Data Dictionary. 

 (it is already in the raw download .zip)

**Comment by diego-** [comment]
S3 assets are currently restricted to authenticated users only.

**Comment by diego-** [comment]
Final queries:

# Sample API Calls

# All Data for Boston College
api.data.gov/collegescorecard/v1/schools?school.name=boston%20college
api.data.gov/collegescorecard/v1/schools?id=164924

# Completion By Race
api.data.gov/collegescorecard/v1/schools?fields=school.name,id,2013.student.demographics.race_ethnicity.white,2013.student.demographics.race_ethnicity.black,2013.student.demographics.race_ethnicity.hispanic,2013.student.demographics.race_ethnicity.asian,2013.student.demographics.race_ethnicity.aian,2013.student.demographics.race_ethnicity.nhpi,2013.student.demographics.race_ethnicity.two_or_more,2013.student.demographics.race_ethnicity.non_resident_alien,2013.student.demographics.race_ethnicity.unknown,2013.student.demographics.race_ethnicity.white_non_hispanic,2013.student.demographics.race_ethnicity.black_non_hispanic,2013.student.demographics.race_ethnicity.asian_pacific_islander&sort=2013.completion.rate_suppressed.overall:desc

# Debt, Earnings, and Repayment
api.data.gov/ed/collegescorecard/v1/schools?fields=school.name,id,2011.aid.median_debt.completers.overall,2011.repayment.1_yr_repayment.completers,2011.earnings.10_yrs_after_entry.working_not_enrolled.mean_earnings&page=100

**Comment by meiqimichelle** [comment]
@diego- Assigning to you for the final task of getting the latest full data download in the right place. You can move to accept after that for review on dev.

**Comment by diego-** [comment]
full download zip updated.

**Comment by jjoteal** [comment]
Getting this error:
![image](https://cloud.githubusercontent.com/assets/12192706/9751584/9e06aaae-5674-11e5-9ef3-3273e79aab8c.png)


Assigning to Diego to accept.

**Comment by diego-** [comment]
Known issue; this is because the files are not publicly accessible prior to
launch. If you get this message, it is hitting the right link in S3.
