### ISSUE TITLE
As a consumer, I would like to be able to sort my search results alphabetically, by distance, etc.  so that the most important results for me based on my criteria show up at the top of the list

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#189]
Working List of Sort Options:
- A-Z
- Nearest (as long as user has entered location as part of their search criteria)
- Lowest Cost Per Year
- Highest Graduation Rate
- Highest Salary After Graduation
- Lowest Monthly Student Loan Payment

@LisaGee thoughts on this list?

- [ ] As the Dept of ED, I want Consumers' Default Sort Order to be Threshold Earnings, so that they understand that earnings are one of the key metrics they should be looking at to assess the "value" of a school https://github.com/18F/college-choice/issues/253
- [x] UI task is in #274 
- [ ] hook up the API to the HTML so one can filter

Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8782835/00c6cb76-2ee6-11e5-81a6-09c8012b53bb.png)

Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8782844/0ab8affa-2ee6-11e5-8e11-878e45a0335a.png)

**Comment by ultrasaurus** [comment]
this depends on a few APIs
- search alphabetically
- index by number (started on this last week, but then paused), then sort by number
- distance from where?

**Comment by ultrasaurus** [comment]
@LisaG could you please specify column names?

**Comment by diego-** [comment]
lowest cost:
highest graduation rate
highest salary after graduation
lowest monthly student payment

**Comment by shawnbot** [comment]
@jjoteal Have you considered what how people will change the sort *order*, in addition to the field? For instance, I'm assuming that people will want to be able to sort by earnings ascending *or* descending.

I think for now we should consider just listing those as separate options in the drop-down rather than adding another UI element, but it's something to consider for the <kbd>icebox</kbd>.

**Comment by jjoteal** [comment]
@shawnbot for the sake of the MVP, I would agree that they would be separate items in the dropdown. In other works for Salary, there would be one option for "Highest Salary After Graduation" and one for "Lowest Salary After Graduation." 

In the future, we may want to consider something like http://colleges.startclass.com/ -- See the "Sorted by " area and note the switcher for "High to Low".

**Comment by LisaGee** [comment]
Seconded. I think for 1.0 having the direction that makes the most logical sense for Students is great. For example, I would definitely sort Earning (aka Salary) by highest at the top. Not sure that as a Student, I would be real keen on looking at the schools that will get me the least amount of money….

**Comment by LisaGee** [comment]
Refinement of options for Sort Order:
I'd like to be able to sort my search results by: Alphabetically, Size, Cost Per Year, Graduation Rate, Salary, & Location

Alphabetically -- A-Z only
Size - Smallest to Biggest
Cost Per Year -- Smallest to Biggest
Graduation Rate -- Biggest to Smallest
Salary -- Biggest to Smallest
Location -- Grouped by State Alphabetically (A-Z), or if they have searched by zip and mile radius, then by distance from the zip.

Referenced from #483

**Comment by LisaGee** [comment]
I think we've implemented the bulk of this story. Closing
