### ISSUE TITLE
As a Consumer, I want to be able to perform an Advanced Search

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#197]
As a Consumer, I want to be able to perform an Advanced Search (Institution Type, Campus/Housing, Selectivity, Diversity, Special Mission) so that I can narrow down my choices more specifically to criteria that is important to me.

From a user experience (story acceptance) perspective, this includes these smaller stories
- [ ] Search by Institution Type (non-profit, for-profit) https://github.com/18F/college-choice/issues/192
- [ ] Search by Campus/Housing https://github.com/18F/college-choice/issues/193
- [ ] Search by Selectivity https://github.com/18F/college-choice/issues/194
- [ ] Search by Diversity https://github.com/18F/college-choice/issues/195
- [ ] Search by Special Mission https://github.com/18F/college-choice/issues/196

**Comment by LisaGee** [comment]
Reducing feature set of this for Launch.
