### ISSUE TITLE
As a product team member, I would like to see analytics for the data site so I can understand how visitors use it

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#332]
+ [ ] All pageviews/impressions https://github.com/18F/college-choice/issues/521
+ [ ] All clicks (links and interactions [like expansion]) https://github.com/18F/college-choice/issues/522
+ [ ] Searches completed https://github.com/18F/college-choice/issues/523
+ [ ] Shares https://github.com/18F/college-choice/issues/524
+ [ ] Record data from all search requests (ie, I want to be able to answer "what's the most popular data summary/filter" etc) https://github.com/18F/college-choice/issues/525
+ [ ] Downloads (#, not identity) https://github.com/18F/college-choice/issues/526

Compliments of @mlm79!

**Comment by LisaGee** [comment]
@ErieMeyer - Can you break this EPIC into stories. One should be for out of the box metrics and then each custom metric should be its own story. Thanks.

**Comment by ErieMeyer** [comment]
It is now epic'd :100:

**Comment by meiqimichelle** [comment]
Update: 18F google analytics are running just fine on our site, and have been for at least a week. As per direction from Lisa, I've been trying to move us over to using DAP alone but have been running into problems in getting DAP to see our site. At this point, I have a help desk request in to DAP because no one at 18F can figure out why we can't see our site there.

**Comment by ErieMeyer** [comment]
@meiqimichelle -- what's the latest?

**Comment by meiqimichelle** [comment]
The helpdesk was helpful :) DAP can see our site, it is just with our low hits we get hidden in many of the dashboards you would normally use to see our stuff. So, we will be contributing to things like `analytics.usa.gov` and other stat roll-ups, no prob. In the meantime, Lisa confirmed that she can get what she needs from the 18F GA account wrt stats for launch.

**Comment by LisaGee** [comment]
I think this Epic can be closed. Google Analytics implemented across site.
