### ISSUE TITLE
As a consumer beta tester, I would like to see the real data on a password-protected site so that I can see how it really works

### ISSUE THREAD

**Issue by shawnbot** [18F/college-choice#357]
There will no doubt be data field mismatch stuff to fix here, since we're trying to make an API that people want to use. Data questions and issues will be addressed elsewhere and linked back here.

#### Search Results
- [x] "under investigation" warnings
- [x] name, city, state
- [x] undergraduate population
- [x] 2-/4-year designation
- [x] net price meter
- [x] graduation rate meter
- [x] average salary meter

#### School Page
- [x] "under investigation" flag
- [x] name, city, state
- [x] undergraduate population
- [x] ownership (public/private)
- [x] locale
- [x] size designation (small/medium/large)
- [x] net price meter
- [x] graduation rate meter
- [x] average salary meter
- Cost:
  - [x] net cost by income level
- Debt:
  - [x] repayment rate meter
  - [x] average total debt
  - [x] average monthly loan payment
  - [x] % of students receiving federal aid
- Graduation & Retention:
  - [x] retention rate meter
- Earnings:
  - [x] average salary after leaving
  - [x] former students earning >$25k (see: #373)
- Student Body:
  - [ ] gender bars (see: #376)
  - [ ] race/ethnicity (see: #371)
  - [ ] average age (see: #374)
- Selectivity:
  - [ ] Selectivity classification (see: #381)
  - [ ] SAT chart(s)
  - [ ] ACT chart
- Academics (see: #371)
  - [x] popular programs
  - [x] available programs

**Comment by shawnbot** [comment]
This is progressing nicely. I've updated the description with a task list for all of the data-related bits, and the only ones remaining as of this comment are the SAT & ACT charts, human-readable labels for race/ethnicity and academic programs, being tracked in #371.

**Comment by shawnbot** [comment]
This is merged into `dev`, and can be previewed on Federalist. I propose closing this in favor of smaller issues (like the ones I've created above) that can be prioritized accordingly. Lisa, all you!

**Comment by LisaGee** [comment]
Accepted. I am able to see the Consumer Tool with real data behind password protection.
