### ISSUE TITLE
As a Consumer, I want to view Basics info about an Indivdual School, so that I can get a good feel for whether it might be a good match for me.

### ISSUE THREAD

**Issue by shawnbot** [18F/college-choice#44]
We should see:

- [x] City and State
- [x] Mini-map (use [Leaflet] ~~or [Pinpoint]~~)
- [x] Type of Institution/"predominant degree" (2-year or 4-year)
- [x] Undergraduate Population
- [x] Special Designation
- ~~Mission Statement~~ (moved to #101)
- ~~Admissions Data~~ (moved to #102)
- ~~Costs & Financial Aid Data~~ (moved to #103 and #104)

![image](https://cloud.githubusercontent.com/assets/113896/8609814/fc3f8f64-265e-11e5-9018-4388a8d48178.png)

This is a follow-up to #2. These are some more granular tasks to support the implementation of the design:

- [x] @ultrasaurus to update the public API so that it surfaces all of the fields needed for the top-level school info
- [x] @jjoteal to provide a mobile design and/or update the comp below to account for information that we're not including in this sprint
- [x] @meiqimichelle to further flesh out the school page style guide to match comps
- [x] @meiqimichelle to find and/or acquire, then integrate, these icons (tracked in #96):
  
  ![image](https://cloud.githubusercontent.com/assets/113896/8576368/4eb5b16a-2556-11e5-85c9-fffffae3470a.png)

[Leaflet]: http://leafletjs.com/
[Pinpoint]: http://dowjones.github.io/pinpoint/

**Comment by shawnbot** [comment]
This is @jjoteal's desktop mockup, which is marked as "IN PROGRESS" on Drive. Jessica, is there anything that we should know before we start stubbing out the basic shape of this page? Specifically, is the anything that we should *not* do because it's in flux or may be removed?

![inprogress-picc-individual-school-desktop](https://cloud.githubusercontent.com/assets/113896/8532705/ffdf0a18-23e4-11e5-90ce-d723a3eb322a.png)

**Comment by jjoteal** [comment]
The main structure of the page is not changing, but there will be some design changes within each of the expand/collapse areas. I would say you could safely move forward with the general layout structure, but hold on the design elements within the expand/collapse containers.

**Comment by LisaGee** [comment]
Hey Jess,

Isn’t a bunch of functionality that you have on this page not going to make it in for 1.0? Definitely the If You Like This School, You May Also Like…. In the right rail.

**Comment by jjoteal** [comment]
Yes, not all of this functionality will be there, but the basic page structure will remain the same. For example, the "If You Like This School" feature will likely NOT be included in our first release, but the "Paying for College" promo will. So, we will still need this 2-column layout. Similarly, we will also likely launch without the "Did You Know" calculator feature, but we still will need the expand/collapse areas and a 1-column layout for the main content area. 

Once I make the design revisions per the feedback yesterday, I can highlight the areas of the comp that can be "skipped" for the first release.

**Comment by shawnbot** [comment]
@ultrasaurus I'm assigning this to you so that you know which fields take priority on the API side.

**Comment by shawnbot** [comment]
Addendum: please re-assign to me when some/all are available in the public API.

**Comment by shawnbot** [comment]
@ultrasaurus @jjoteal @meiqimichelle @LisaGee I updated the issue description to list some more granular tasks for this to be completed. I think we're going to need a tighter feedback loop to get all of this done in this sprint; otherwise, we'll need to exclude some of those informational bits.

I see the API as the biggest blocker here, because Sarah and I have identified some issues with the data that suggest it'll be a while before we can get the admissions, enrollment and financial data into the test API with some reasonable degree of usefulness. One way that we can get around this is to design the page with fake (i.e. realistic-but-random) data for those fields, and focus our efforts on the design for this sprint.

**Comment by LisaGee** [comment]
Can you extrapolate a bit more on: “it'll be a while before we can get the admissions, enrollment and financial data into the test API with some reasonable degree of usefulness”

Is that a data issue that has been communicated to Clare? (If so, can you refresh me which subject to search on, cause I’ll follow up).
Or is it that the data needed is all there, just not in the actual file structure in a way that is especially helpful?

**Comment by shawnbot** [comment]
Updated the tasks with what's been done so far in #94.

**Comment by shawnbot** [comment]
@LisaGee: as far as I understand, our most recent data drop didn't include values for median earnings. From what I've seen, the values for admission and completion rates are also super sparse (i.e., the values for most schools are null).

**Comment by shawnbot** [comment]
@LisaGee I propose striking everything below the top 3 charts (cost/year, graduation rate, and average salary) to make this story achievable in this sprint. Then we can add stories for each section further down the page so we can prioritize check them off the list individually, rather than having this big, hulking story looming over us, unfinished, for the next couple of weeks.

**Comment by shawnbot** [comment]
Description updated to reflect new stories/issues for more specific areas of the page.

**Comment by shawnbot** [comment]
Description updated with a more specific snapshot of the comp, and an additional task for the "Special Designation". @LisaGee, can you tell us where that comes from in the data?

**Comment by shawnbot** [comment]
@meiqimichelle This is all you now!

**Comment by meiqimichelle** [comment]
This is blocked by lack of icons ( #96 ). In the meantime, we will be much closer (other than icons) with the merge of #141.

@shawnbot I'm not sure if the designations are displaying the way you expected. They look like this right now:
![screenshot 2015-07-14 22 10 26](https://cloud.githubusercontent.com/assets/4827522/8691273/32dfdb9a-2a75-11e5-91ce-4182ae87b21c.png)

Entirely possible that you haven't gotten there yet. Also, I want to chat with you about how to switch out the icons as well as the words in response to the data.

**Comment by meiqimichelle** [comment]
For the record, we're here now:
![screenshot 2015-07-15 22 08 10](https://cloud.githubusercontent.com/assets/4827522/8715896/0b46b4ea-2b3e-11e5-8e83-962a7cc02972.png)

**Comment by LisaGee** [comment]
I don't think is blocked anymore.

**Comment by barkimedes** [comment]
@meiqimichelle From what I can tell, this seems done. Can we close this issue?
