### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by shawnbot** [18F/college-choice#729]
- [x] @LisaGee decide what our URL should be
- [x] @diego-  coordinate with api.data.gov folks to get that URL ready
- [x] @LisaGee register a new, dedicated API key for the production site
- [x] @meiqimichelle create pull request with `sitemap.xml` from @dnesting with version that contains real URL (see: #496)
- [x] @meiqimichelle update `robots.txt` to refer to the new sitemap
- [x] @shawnbot update Federalist config and deployment docs with the production API URL, API key, and [custom domain](https://github.com/18F/college-choice/issues/1262#issuecomment-139593987)
- [x] @shawnbot merge PR to `master` branch to trigger a rebuild of the site and push it to S3
- [x] @ozzyjohnson point Amazon CloudFront at the S3 bucket

**Comment by LisaGee** [comment]
We know the name of the site. We should make use of it for the API.
@ErieMeyer - Can I charge you with getting this set up in conjunction with @diego- properly? Thanks.

Moved from #422

**Comment by ErieMeyer** [comment]
Started a thread with @gbinal and @diego-

**Comment by diego-** [comment]
last checkbox to @shawnbot

**Comment by shawnbot** [comment]
@diego- @ultrasaurus what do you all think about having a new, dedicated API key for the production site? Maybe @LisaGee could register for a new one on api.data.gov?

**Comment by LisaGee** [comment]
Lisa found it and sent it to @shawnbot

**Comment by LisaGee** [comment]
need to redeploy with new key

**Comment by shawnbot** [comment]
Assigning to @dnesting for the sitemap task.

**Comment by shawnbot** [comment]
I added a note about pointing Amazon CloudFront at S3.

**Comment by shawnbot** [comment]
Just copying this here from Dave's [very helpful comment](https://github.com/18F/college-choice/issues/1262#issuecomment-139593987):

> Just so we have it documented, there are two steps to activate the custom domain:

> 1. Set the custom domain in Federalist. This is actually a full URL, from protocol to TLD, no trailing slash. This tells Federalist to build the site without a baseurl and sets your "View site" link to go to the custom domain. This needs to be done by @shawnbot as the owner of the site on Federalist.
    <img width="638" alt="screen shot 2015-09-11 at 12 31 15 pm" src="https://cloud.githubusercontent.com/assets/170641/9820342/465a080a-5881-11e5-8fc9-894ea01442bd.png">
> 2. Set the CloudFront distribution's `origin path` to `/site/18F/college-choice`, and set the default behavior to redirect http to https. @ozzyjohnson or I can help with this step.
    <img width="386" alt="screen shot 2015-09-11 at 12 36 12 pm" src="https://cloud.githubusercontent.com/assets/170641/9820435/f5dd3c66-5881-11e5-9f25-66857d8bbbd5.png">

**Comment by ozzyjohnson** [comment]
FYI @shawnbot @hollyallen @diego- step #2 above is what we talked about this morning. The HTTP to HTTPS redirection is done.

@dhcole - We talked about 15 minutes to propagate the change. During that time are hits going to resolve to the old, blank placeholder or punch through to S3?

**Comment by dhcole** [comment]
@ozzyjohnson CloudFront changes roll through their fleet of servers, so as an edge server gets the update, it will switch its origin from the placeholder page to the actual site. The whole process takes about 15 minutes. Individual edge servers will update on a rolling basis throughout that duration. So users may see the change sooner or later in that window, depending on where they are located. Does that answer your question?

**Comment by ozzyjohnson** [comment]
@dhcole Yes, thanks.

**Comment by barkimedes** [comment]
@LisaGee Closeable? Seems like we launched :smiling_imp: : :us:

**Comment by LisaGee** [comment]
Agreed!
