### ISSUE TITLE
Include in the results, all school who offer and award an associates or bachelors degree

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#951]
Tasks remaining for this issue to be completed (thanks @abisker)
- [x] Check in the data.yaml file https://github.com/18F/college-choice-data/pull/8
- [x] deploy new API code to dev server https://github.com/18F/open-data-maker/issues/268
- [x] write up manual steps to migrate index snapshots so we can reindex using the new data.yaml file
- [x] Reindex and move to a staging environment
- [x] Integrate json test data to alt-search https://github.com/18F/college-choice/pull/1422 
- [x] Update the frontend code to query for the correct set of schools 
- [x] Provide icon for predominantly certificate schools (#1396)
- [x] Update expected numbers in automated tests to reflect the newly-included schools

Some expected results:
* total # of schools: 4247
* schools that offer an associates degree: 3056
* schools that offer a bachl degree: 2671

(3587 is old number)

Rather than using PREDDEG==2 || 3, we should use HIGHDEG==2 || 3

an example of this is:  https://github.com/18F/college-choice/issues/1096

**Comment by shawnbot** [comment]
This is a straightforward change from using `school.degrees_awarded.predominant` to `school.degrees_awarded.highest`.

**Comment by shawnbot** [comment]
Question, @LisaGee: should we be using HIGHDEG anywhere else, or *just* in search, and only if the user hasn't filtered on Associates or Bachelors degree? In those cases, should we filter on HIGHDEG or still use PREDDEG?

**Comment by shawnbot** [comment]
Actually, @LisaGee, I'm pretty sure that this is not what we want. There are a lot of schools with PREDDEG==2|3 and HIGHDEG>3 — i.e., any school that offers graduate degrees. This change removes those schools from the search results. Moving this to blocked for resolution.

**Comment by LisaGee** [comment]
I think you're right. I think what we want (as noted in #885 - doh):
Any school where:
1. (PREDEG==2||3) && (PREDDEG==1 && HIGHDEG!=1)

**Comment by LisaGee** [comment]
To recap: We want to include predominantly certificate schools, but only if they offered at least one two- or four-year degree.
1.	Include any school where preddeg=2 or preddeg=3
2.	Include any school where preddeg=1 if highdeg!=1 
3.	Exclude schools with preddeg=0
4.	Exclude schools with preddeg=4 (still confirming, but I think this is the only thing that's doable given our data).

**Comment by ultrasaurus** [comment]
so school.degrees_awarded.predominant__range=1..3&school.degrees_awarded.highest__range=2..4 ?

**Comment by LisaGee** [comment]
That ought to do it. Thanks! I'm a little too close on this one.

**Comment by LisaGee** [comment]
Need to re-review with Ted - see email

**Comment by barkimedes** [comment]
@claremccann Is it possible to get RTI to add columns to the data? The first column being whether a 2-year degree is offered and the second being whether a 4-year degree is offered?

**Comment by claremccann** [comment]
To clarify, you would need the highdeg category broken out, so rather than saying "a school offers an associate degree if highdeg==2 and a bachelor's if highdeg==3," you need two different columns that say "associatedeg==1 means it offers an associates" and "bachelorsdeg==1 means it offers a bachelor's"? Am I understanding correctly?

Also, can we include data elements in the file without adding them to the API, or would this necessitate adding new things to the API at the same time?

**Comment by barkimedes** [comment]
Yes! I think that those associatedeg and bachelorsdeg fields sound good to me!

I am not sure I understand the second question; are you asking if data changes are automatically updated in the API? If so, I would say that the best way to think about it is as a multi-step thing--once we have the additional columns, we will then be able to do whatever work is necessary to expose those columns through the API. Does that help or were you asking something else?



-----Original Message-----

**Comment by claremccann** [comment]
I think that helps. In other words, adding new columns doesn't affect the API? I'm surprised to hear that because there were a lot of specifications put on our data files to ensure they didn't mess up the API -- just want to make sure.

**Comment by claremccann** [comment]
Also, would it just be easier to say "include if highest degree (highdeg) does not equal 1 (certificate)"?

**Comment by barkimedes** [comment]
@claremccann Its more like the API is built on top of the data. So when new columns are added, we can update the API to use those columns. Conversely, if the existing columns were to change, the API would explode. Also, in order to build an API from any data, it has to be consistent, well-structured, etc. So I suspect whatever specifications you had are probably related to those things.

Do you have any idea how long a data update like this (adding the two columns) would take?

@hollyallen Just for my own edification, what is the process on our end for updating the data so that we can add it to the API? For example, who updates the data dictionary? I know open data maker does a lot for us, but I want to make sure I understand the necessary inputs and their courses.

Thanks :usa:


-----Original Message-----

**Comment by claremccann** [comment]
Can I consider this license to add other, new columns without worrying about the API at this point?

We will try to produce in the next data run as needed.

**Comment by hollyallen** [comment]
Please do add more data fields, this ticket is an excellent example of that need. The backend service might need to be updated if the types of data in any given column changed, as @barkimedes said.

If I remember correctly, RTI made the updates to the data dictionary. @ultrasaurus can correct me if that is wrong though.

**Comment by hollyallen** [comment]
I talked with @ultrasaurus who said that the data dictionary starts as a google spreadsheet updated by @claremccann , then it is exported as a csv for the /data site and turned into the data.yml file for the back end service by a script.

**Comment by barkimedes** [comment]
@hollyallen: Thanks for the info!

The other question I had (we talked about it a little on the call earlier) is if we can handle 'or's in the tool . You mentioned that elasticsearch may be able to create a column when it ingests data.

The reason I ask is because we are requesting 2 columns to be added to the data (associatedeg and bachelorsdeg). But if we want all the schools that offer either/both associates or bachelors, can we handle that using the tool? Or do we need to request a third column to be added to the data to represent at least one of them is available?

**Comment by hollyallen** [comment]
@ultrasaurus My idea was to create a new document attribute during the data import process which is 1 if either associatedeg==1 or bachelorsdeg==1. Seem reasonable?

**Comment by ultrasaurus** [comment]
current thinking is that this approach should work from my comment on Sep 3:  school.degrees_awarded.predominant__range=1..3&school.degrees_awarded.highest__range=2..4 ?

**Comment by hollyallen** [comment]
@ultrasaurus your search criteria would also return PREDDEG=4 schools, but I think Shawn is saying that the front end filter thought out so it would be okay?

**Comment by hollyallen** [comment]
While this ticket might be doable w/o the associatedeg==1 and bachelordeg==1 fields, I believe #952 and #953 are not. 

It will probably be faster to go ahead with the plan @ultrasaurus said and use that query. We might consider a cleanup ticket to use the new data fields when they are available. 

If these three tickets can only go out together, not piecemeal, we'll need to wait for the data.

**Comment by claremccann** [comment]
So just to clarify: What you want is two new fields added. One that is "preddeg means it should be there" and the other that is "highdeg means it should be there" (so binary variables of preddeg=1, 2, or 3 and highdeg=2, 3, or 4). Yes?

**Comment by LisaGee** [comment]
@claremccann Sorry. I think there has been confusion as there are so many different channels by which we are communicating. Clare on 9/21, I sent you and email asking for the following: "Could you get RTI to create 3 new columns: Offers Associates, Offers Bachelors, and Offers Associates OR Bachelors?"
If we get this, we should be all set. Thanks and sorry for the multiple requests from different people in different places.

All - Let me know if there are any other questions. Thanks.

**Comment by ultrasaurus** [comment]
Via email from Sabrina:

We want to require CIPxxASSOC or CIPxxBACHL > 1.
 
but also make sure they are awarding degrees, not just offering them, so we do not want to include any of the PREDDEG = 0, HIGHDEG = 1, or PREDDEG=4 schools.

I think we want this kind of a query, which we can do
```
PREDDEG 1..3 &
HIGHDEG 2..4
```

in data.yml we could (potentially) create a computed field, like:
CIPxxASSOC or CIPxxASSOC or CIPxxASSOC or CIPxxASSOC

**Comment by ultrasaurus** [comment]
I've got some local open-data-maker changes that let me do queries like this:

http://localhost:3000/v1/schools?_per_page=3000&fields=id,school.name,2013.academics.program.bachl&2013.academics.program.bachl=1&school.degrees_awarded.predominant__range=1..3&school.degrees_awarded.highest__range=2..4

http://localhost:3000/v1/schools?_per_page=3000&fields=id,school.name,2013.academics.program.assoc&2013.academics.program.assoc=1&school.degrees_awarded.predominant__range=1..3&school.degrees_awarded.highest__range=2..4

**Comment by barkimedes** [comment]
@ultrasaurus I figured out the differences. There are a couple more constraints we need to add to your query:

UGDS > 0 (meaning students are enrolled - your results include a few UGDS = NULL schools)
CURROPER = 1 (meaning that it is currently operating - your results include CURROPER = 0 schools)

```
PREDDEG 1..3 &
HIGHDEG 2..4 &
CURROPER = 1 &
UGDS > 0
```

Lastly, we need to loosen up query a bit. Right now, you're only returning schools that have at least one CIPxxASSOC = 1 or CIPxxBACHL = 1. But there are some schools that only have CIPxxASSOC = 2 or CIPxxBACHL = 2. So they're being left out. Example school: 110556 (California State University-Fresno only offers CIPxxBACHL = 2)

Let me know if you have any questions--that accounted for all of the discrepancies I saw.

**Comment by ultrasaurus** [comment]
@barkimedes thanks so much for the detailed follow-up!  All makes sense, just one question:

What does it mean when  `CIPxxBACHL = 2` ?  I'm  trying to figure out if `2013.academics.program.bachl` should be `2` or `true` (I think the latter, but need to understand a little more about what this data means)

**Comment by barkimedes** [comment]
I'm not 100% sure on what the 2 vs 1 means for CIPxxASSOC/CIPxxBACHL means, but I do know the answer to your question is that the new column should be a boolean. so 2013.academics.program.bachl and 2013.academics.program.assoc should be boolean values.

Thanks!!

**Comment by claremccann** [comment]
1=program offered
2=program offered as distance ed (fully online)

**Comment by barkimedes** [comment]
@claremccann Thanks for the info!

@ultrasaurus, I checked my set of schools with the data I got from ed, and it matched exactly. EXACTLY :smile: :us: I'm now confident that we have the right set of schools given the update to the queries I mentioned a few days ago.

**Comment by mitzkow** [comment]
Yeah!

Sent from my Windows Phone
________________________________

**Comment by barkimedes** [comment]
#1396 must also be done for this story to be complete (otherwise we'll introduce a bug).

**Comment by barkimedes** [comment]
Tasks remaining for this issue to be completed
- [ ] Check in the data.yaml file https://github.com/18F/college-choice-data/pull/8
- [ ] Complete script to migrate index snapshots so we can reindex using the new data.yaml file
- [ ] Reindex and move to a staging environment
- [ ] Deploy to production with new index
- [ ] Update the frontend code to query for the correct set of schools 
- [ ] Provide icon for predominantly certificate schools (#1396)

**Comment by yozlet** [comment]
It appears that the snapshot migration script and associated tools don't quite do what I thought they did, or I've misunderstood something about how to use them - am checking with @ozzyjohnson. In the meantime, the `indexing` space has reindexed the data with the new boolean code & config. I've used a slightly more manual process to copy the index over to `dev`, and am poking at the data looking at examples from @barkimedes.

**Comment by yozlet** [comment]
Given what I've seen from indexing with the new `data.yaml`, we have a logic problem and a naming problem. (This is all based on a sample from [one school record](https://ccapi-dev.18f.gov/v1/schools?id=173966), and may need wider investigation.)

**Logic problem:** There appear to be zero records with any of the three new calculated fields (`YEAR.academics.program.assoc/bachl/assoc_or_bachl`) set to `false`. In the case of [this school](https://ccapi-dev.18f.gov/v1/schools?id=173966), all the `2013.academics.program.bachelors.*` fields are set to `0`, yet `2013.academics.program.bachl` is `true`. I'm diving into this one first.

**Naming problem:** For bachelors' degrees we're adding topic subkeys below the 'YEAR.academics.program.bachelors' key (for example, '2007.academics.program.bachelors.computer`). For the new summary booleans we're using the shortened form, `bachl`. However, for associates' degrees we've used the shortened form `assoc` for **both topic subkeys  the new summary boolean**. This is bad, because when the summary boolean is calculated it clobbers the hash of topic subkeys that was previously under `assoc` and replaces them with this one boolean.

Ideally, we'd have done the naming for associates' degrees the same way we did bachelors - use the long form name (`associates`) as the parent for the topic subkeys, and the shortened form (`assoc`) for the summary boolean. And it'd be great (and easy) to move to that, except that we potentially break the API for existing users by renaming a load of existing keys. Alternatively we use `associates` for the summary boolean and nobody has to change anything other than now dealing with the shudders of horror when we look at our loudly inconsistent naming scheme. A third solution involves grouping the summary booleans under their own key in the `YEAR.academics.program.*` space so they don't collide with existing ones. (There are probably other solutions too.) **Your opinions are welcome.**

**Comment by barkimedes** [comment]
@yozlet I think I prefer option 3. IMHO, we don't want to break folks trying to get out this feature (option 1), and I think we shouldn't compound bad decisions (option 2). 

I don't know if anyone would like this idea, but another naming option is `YEAR.academics.program.assoc.any` and `YEAR.academics.program.bachelors.any`. Thoughts?

**Comment by yozlet** [comment]
@barkimedes I like that idea! I like it so much that I'm kind of torn between it and my original proposal. :smile:

**Comment by yozlet** [comment]
In the meantime, @ultrasaurus & I dove into the logic problem and we have a fix here: https://github.com/18F/open-data-maker/pull/262

I've started a new index run now with the fix (though it isn't merged yet) and a new `data.yaml` which has @barkimedes suggestions for renamed fields ([pull request here](https://github.com/18F/college-choice-data/pull/9)). If it all looks good in the morning we'll copy it over to `dev`.

**Comment by yozlet** [comment]
Indexing is done and looks good! Also (per #1096) Columbus State Community College is in, and has correct summaries: https://ccapi-indexing.18f.gov/v1/schools?school.name=Columbus%20State%20Community%20College&fields=id,school.name,2012.academics.program.assoc.any,2012.academics.program.bachelors.any,2012.academics.program.assoc_or_bachelors.any

Now to copy this index over to dev.

**Comment by ultrasaurus** [comment]
New query with new name:  https://ccapi-dev.18f.gov/v1/schools?sort=2011.earnings.6_yrs_after_entry.percent_greater_than_25000%3Adesc&school.degrees_awarded.predominant__range=1..3&school.degrees_awarded.highest__range=2..4&school.operating=1&2013.academics.program_available.assoc_or_bachelors=true&fields=id%2Cschool.name%2Cschool.city%2Cschool.state%2C2013.student.size%2Cschool.ownership%2Cschool.degrees_awarded.predominant%2C2013.cost.avg_net_price.overall%2C2013.completion.rate_suppressed.overall%2C2011.earnings.10_yrs_after_entry.median%2C2011.earnings.6_yrs_after_entry.percent_greater_than_25000%2Cschool.under_investigation

**Comment by yozlet** [comment]
Have written up docs on _manually_ copying indexes from one space/app to another: https://github.com/18F/college-choice-data/blob/master/doc/snapshot.md

**Comment by barkimedes** [comment]
:us: :smile: :+1: :us:
