### ISSUE TITLE
After launch, check to see that meta tags are working

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#974]
- [x] should display nicely in Twitter [here](https://cards-dev.twitter.com/validator)
- [x] should display nicely in Facebook [here](https://developers.facebook.com/tools/debug/og/object/)
- [x] should display nicely in places like Slack (image, correct url, etc)
- [x] return to google Site Console and verify ownership. [info](https://support.google.com/webmasters/answer/35659?vid=1-635767545005026055-4005020357)
- [x] submit our site to the google bots
- [x] incorporate copy changes from #1291 into the `description` meta

**Comment by meiqimichelle** [comment]
@LisaGee Just to note, we can't actually do this till after soft launch. I'm not sure if you want a different label for that (ie, it will have to come after code freeze and we're at our url).

**Comment by LisaGee** [comment]
@meiqimichelle Let's just make it blocked for the moment.

**Comment by shawnbot** [comment]
FWIW, we can test this on the Federalist S3 URL right now.

**Comment by shawnbot** [comment]
Twitter wants a `twitter:text:title`:

![image](https://cloud.githubusercontent.com/assets/113896/9802831/0788a79e-57d2-11e5-9044-f406e55e82db.png)

**Comment by shawnbot** [comment]
Slack doesn't display an image:

![image](https://cloud.githubusercontent.com/assets/113896/9802855/3365336e-57d2-11e5-943b-6209f945983e.png)

**Comment by shawnbot** [comment]
[Facebook's Object Debugger](https://developers.facebook.com/tools/debug/og/object/) wants an absolute `og:url`:

![image](https://cloud.githubusercontent.com/assets/113896/9802911/b2524b4e-57d2-11e5-81b1-0d68e66cd9f8.png)

but it shows this:

![image](https://cloud.githubusercontent.com/assets/113896/9802952/00b67418-57d3-11e5-8937-00c36c1be81b.png)

**Comment by shawnbot** [comment]
I think the thing to do here might be to have our production config set `site.baseurl` to the full-qualified URL. Either that, or have another URL (maybe `site.permalink`?) that gets used in `og:url`.

**Comment by meiqimichelle** [comment]
Sorry, how did you test that? I get auth errors with Federalist since it is behind, well, auth, but I'm guessing from this chain that you know a different way to access @shawnbot . If you let me know I can prep a PR for right after launch.

**Comment by shawnbot** [comment]
The [Facebook Object Debugger](https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2Fcollegescorecard.ed.gov) suggests that we should be using `og:image` instead of `og:img`.

![image](https://cloud.githubusercontent.com/assets/113896/12524425/d7359904-c111-11e5-9e8b-110fd716dad1.png)

**Comment by shawnbot** [comment]
The Facebook issues and _hopefully_ the Google school page indexing issue should be addressed in #1458. :fingers-crossed:

**Comment by shawnbot** [comment]
We will be able to test this once #1458 gets merged to production.

**Comment by abisker** [comment]
@shawnbot are we able to take a look at this now?

**Comment by shawnbot** [comment]
@abisker yep, I think the thing to test next is whether we need to resubmit the site with the `https://` URL, as I mentioned [here](https://github.com/18F/college-choice/issues/496#issuecomment-180584736). These issues are a bit tangled... I would suggest closing this one (now that the meta tags are in order) and closing #496 in favor of #1495. cc @barkimedes

**Comment by shawnbot** [comment]
Well, the site has been submitted and we can see it via the Site Console, so those things are done. The only thing that seems unresolved is the potential HTTPS issue I linked to above, in which it's possible that Google is not indexing our school pages because the HTTP URLs redirect to HTTPS.

**Comment by abisker** [comment]
@shawnbot are we able to resolve the HTTPS issue now? Or if not, what's needed in order to do so?

**Comment by shawnbot** [comment]
@abisker I dropped [a comment](https://github.com/18F/college-choice/issues/1495#issuecomment-190375356) in #1495 after observing some schools indexed. I'd like to take another look at the site console, but I think that this issue should be closed and moving the indexing discussion to 1495.

**Comment by abisker** [comment]
@barkimedes are you good with the above?

**Comment by barkimedes** [comment]
SGTM :+1:
